version: "3.8"
services: 
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: busca_cep
    ports:
      - 5432:5432
    restart: on-failure

  redis:
    image: "redis:5-buster"
    container_name: redis
    ports:
      - "6379:6379"
